# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_Camera.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 784)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openCamera = QtWidgets.QPushButton(self.centralwidget)
        self.openCamera.setGeometry(QtCore.QRect(20, 120, 161, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.openCamera.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.openCamera.setFont(font)
        self.openCamera.setObjectName("openCamera")
        self.SHOW = QtWidgets.QLabel(self.centralwidget)
        self.SHOW.setGeometry(QtCore.QRect(210, 10, 271, 331))
        self.SHOW.setObjectName("SHOW")
        self.TakePicture = QtWidgets.QPushButton(self.centralwidget)
        self.TakePicture.setGeometry(QtCore.QRect(800, 300, 91, 31))
        self.TakePicture.setObjectName("TakePicture")
        self.showpictures = QtWidgets.QLabel(self.centralwidget)
        self.showpictures.setGeometry(QtCore.QRect(500, 30, 250, 150))
        self.showpictures.setObjectName("showpictures")
        self.showpictures2 = QtWidgets.QLabel(self.centralwidget)
        self.showpictures2.setGeometry(QtCore.QRect(500, 190, 250, 150))
        self.showpictures2.setObjectName("showpictures2")
        self.signin = QtWidgets.QPushButton(self.centralwidget)
        self.signin.setGeometry(QtCore.QRect(1000, 300, 93, 28))
        self.signin.setObjectName("signin")
        self.nameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.nameInput.setGeometry(QtCore.QRect(890, 170, 113, 21))
        self.nameInput.setObjectName("nameInput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(810, 170, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 220, 72, 15))
        self.label_2.setObjectName("label_2")
        self.idInput = QtWidgets.QLineEdit(self.centralwidget)
        self.idInput.setGeometry(QtCore.QRect(890, 220, 113, 21))
        self.idInput.setObjectName("idInput")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 23))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openCamera.setText(_translate("MainWindow", "打开摄像头"))
        self.SHOW.setText(_translate("MainWindow", "摄像头"))
        self.TakePicture.setText(_translate("MainWindow", "拍照"))
        self.showpictures.setText(_translate("MainWindow", "照片1"))
        self.showpictures2.setText(_translate("MainWindow", "照片2"))
        self.signin.setText(_translate("MainWindow", "注册"))
        self.nameInput.setPlaceholderText(_translate("MainWindow", "按下回车键结束"))
        self.label.setText(_translate("MainWindow", "姓名"))
        self.label_2.setText(_translate("MainWindow", "学号"))
        self.idInput.setPlaceholderText(_translate("MainWindow", "按下回车键结束"))

